!!com.example.app.properties.PropertiesData
appiumProperties:
  platformName: android
  deviceName: Samsung Galaxy S23 API 31
  udid: emulator-5554
  app:
  automationName: UIAutomator2
  newCommandTimeout: 120
  autoGrantPermissions: true
